baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Aptly'
[module]
    [[module.imports]]
        path = "github.com/imfing/hextra"

[params]
  version = "1.5.0"
[params.navbar]
  displayTitle = true
  displayLogo = true
  width = "full"
  [params.navbar.logo]
    path = 'images/logo.svg'
[params.footer]
  width = "full"
[params.page]
width = "full"
[params.theme]
  default = "light"
  displayToggle = true

[[menu.main]]
  name = "Documentation"
  pageRef = "/docs"
  weight = 1
[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 2
[[menu.main]]
  name =  "Search"
  [[menu.main.params]]
    type = "search"
  weight = 4
[[menu.main]]
  name = "Github"
  url =  "https://github.com/aptly-dev/aptly"
  [[menu.main.params]]
    icon = "github"
  weight = 5
